sudo: false
language: generic
matrix:
  include:
    - os: linux
cache:
  directories:
    - "/tmp/texlive"
    - "$HOME/.texlive"
  timeout: 7200
before_install:
  - bash ./travis_setup.sh
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"

script:
  - latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape masterthesis.tex

after_success:
  - bash ./utilities/deploy.sh
  deploy:
    provider: releases
    api_key: $release_key
    file:
      - thesis-gwu.zip
      - masterthesis.pdf
    skip_cleanup: true
    on:
      repo: frank1789/MasterThesis
      tags: true
      branch: master