sudo: require
dist: xenial
language: bash

branches:
  only:
    - develop

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-full
  - sudo apt-get install -y biber
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
  
script:
  - make
