sudo: false
language: generic
matrix:
  include:
    - os: linux
cache:
  directories:
    - "/tmp/texlive"
    - "$HOME/.texlive"
  timeout: 7200
before_install:
  - bash ./travis_setup.sh
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"

script:
  - latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape masterthesis.tex

# after_success:
#   - bash ./utilities/deploy.sh
before_deploy:
# Set up git user name and tag this commit
  - git config --local user.name frank1789
  - git config --local user.email francesco.argentieri89@gmail.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $release_key
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  file:
    - masterthesis.pdf
  skip_cleanup: true
  on:
    repo: frank1789/MasterThesis
    tags: true
    branch: master
      