sudo: require
dist: xenial
language: bash

branches:
  only:
    - develop

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-full texlive-publishers texlive-science texlive-pstricks texlive-pictures texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng
  - sudo apt-get install -y biber
  
script:
  - make
