sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  timeout: 7200
before_install:
- bash ./travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape masterthesis.tex
after_success:
- bash ./utilities/deploy.sh
deploy:
  provider: releases
  api_key:
    secure: LsJrRsjNYuLt3p9y/e+BSTACnF+Mxe0fntyuk1zXEHRMHNs8T31awA5avNy11brYTXTJKbmI0lA2NshHqDYJkTOYKPMu3jQJ93Cuiar0qB70HcGwkCXmZADR3w8gRKGylUleXU17ewjdeSTWdnj5DR/vXD/yomUNZCNgtSLTZrs4QIClp7oahb34/FgtBbu5irUBm/WgVyFSlmV98GRqkaanUwZEmN0O7CbtMR2fviMD+JmQb2ovae6bF2Lx5dZYMxyxpRcwpQK94GcFhIVlq8rKkJCDx5M/G6IG5CLjfOBlLkcbLOff5Q+F4nJc7MR55W4m25DFifDbmuTtAYcwpoKKaqJdwX51hlYUWzfpaZKqrI62sOJFGDu27w+ej60F/AMgycrx5vp3PmHPLv67e8LC7XHQ4ugo9MgqrfMkUxtWOlHYweMQbcLaPsKSrBY2YFz5VvBho084BzBnUJCknHH4Lrxc1Mbta5blt0A7E5qGPDs04jMbK0P12qBhjhQ1+4pkWKWm5KTs0HbsvUWc+t/hjdi8r/1LUnC1/2KJTWvUgy6ofZ7JYKwcNOyiUv5aZf1SaVfrZ4fG9w7kMzMV7Paujdg6acDD2H6BY5lxnyvatgwp0JoChK1YwTWeOyASbv4SZILv+BjGfJG3krWlFyQyO2S6tVGIieTDhLbYnd8=
  file: masterthesis.pdf
  on:
    repo: frank1789/MasterThesis
    tags: true
    branch: master
